name: Deploy Graph to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pandas matplotlib elasticsearch

    - name: Generate Graph
      run: python plot.py

    - name: Prepare Jekyll structure
      run: |
        mkdir -p docs/assets/css
        
        echo '---
        ---
        
        @import "{{ site.theme }}";
        ' > docs/assets/css/style.scss
        
        echo 'theme: jekyll-theme-primer
        title: Mi portafolio de cómputo
        description: Visualizaciones generadas
        ' > docs/_config.yml
        

        echo '---
        layout: default
        ---
        

        
        visualizaciones generadas:
        
        ![Gráfico generado](./grafico.png)
        ' > docs/index.md
        
        cp *.png docs/ 2>/dev/null || true
        cp *.jpg docs/ 2>/dev/null || true
        cp *.jpeg docs/ 2>/dev/null || true
        cp *.svg docs/ 2>/dev/null || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs