name: Build and deploy graph

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib elasticsearch

      - name: Run script
        env:
          ES_HOST: "http://localhost:9200"
          ES_USER: "elastic"
          ES_PASSWORD: "password"
        run: python plot.py

      - name: Ensure docs directory exists
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          echo "<html><body><h1>GitHub Pages está funcionando</h1></body></html>" > docs/index.html

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
